# Generated by Django 5.2.4 on 2025-07-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_usertoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserToken",
        ),
    ]
